create table if not exists public.notes (
    id bigint generated by default as identity primary key,
    title text not null,
    created timestamptz not null default timezone('utc', now()),
    updated timestamptz not null default timezone('utc', now())
);

alter table public.notes enable row level security;

create or replace function public.handle_notes_update()
returns trigger
language plpgsql
as $$
begin
    new.updated = timezone('utc', now());
    return new;
end;
$$;

drop trigger if exists handle_notes_update on public.notes;
create trigger handle_notes_update
    before update on public.notes
    for each row
    execute procedure public.handle_notes_update();

create table if not exists public.notes_items (
    id bigint generated by default as identity primary key,
    list_id bigint not null references public.notes(id) on delete cascade,
    child boolean not null,
    title text not null,
    position integer not null,
    created timestamptz not null default timezone('utc', now()),
    updated timestamptz not null default timezone('utc', now()),
    check_time timestamptz default null,
    update_index bigint not null
);

alter table public.notes_items enable row level security;

create or replace view public.notes_with_counts
with (security_invoker = true) as
select
    notes.id,
    notes.title,
    notes.created,
    notes.updated,
    count(notes_items.id)::int as items_count,
    count(notes_items.id) filter (where notes_items.check_time is null)::int as undone_items_count
from public.notes
left join public.notes_items
    on notes_items.list_id = notes.id
group by notes.id, notes.title, notes.created, notes.updated;

create or replace function public.handle_notes_items_update()
returns trigger
language plpgsql
as $$
begin
    if new.update_index <= old.update_index then
        raise exception
            '%',
            json_build_object(
                'id',
                'update_index_conflict',
                'text',
                format(
                    'update_index must be greater than current value (current %s, got %s)',
                    old.update_index,
                    new.update_index
                ),
                'current_update_index',
                old.update_index,
                'requested_update_index',
                new.update_index
            )::text;
    end if;

    new.updated = timezone('utc', now());
    return new;
end;
$$;

drop trigger if exists handle_notes_items_update on public.notes_items;
create trigger handle_notes_items_update
    before update on public.notes_items
    for each row
    execute procedure public.handle_notes_items_update();

drop policy if exists notes_select on public.notes;
create policy notes_select
    on public.notes
    for select
    to anon, authenticated
    using (true);

drop policy if exists notes_insert on public.notes;
create policy notes_insert
    on public.notes
    for insert
    to anon, authenticated
    with check (true);

drop policy if exists notes_update on public.notes;
create policy notes_update
    on public.notes
    for update
    to anon, authenticated
    using (true)
    with check (true);

drop policy if exists notes_delete on public.notes;
create policy notes_delete
    on public.notes
    for delete
    to anon, authenticated
    using (true);

drop policy if exists notes_items_select on public.notes_items;
create policy notes_items_select
    on public.notes_items
    for select
    to anon, authenticated
    using (true);

drop policy if exists notes_items_insert on public.notes_items;
create policy notes_items_insert
    on public.notes_items
    for insert
    to anon, authenticated
    with check (true);

drop policy if exists notes_items_update on public.notes_items;
create policy notes_items_update
    on public.notes_items
    for update
    to anon, authenticated
    using (true)
    with check (true);

drop policy if exists notes_items_delete on public.notes_items;
create policy notes_items_delete
    on public.notes_items
    for delete
    to anon, authenticated
    using (true);
