create table if not exists public.notes (
    id bigint generated by default as identity primary key,
    title text not null,
    created timestamptz not null default timezone('utc', now()),
    updated timestamptz not null default timezone('utc', now())
);

create or replace function public.handle_notes_update()
returns trigger
language plpgsql
as $$
begin
    new.updated = timezone('utc', now());
    return new;
end;
$$;

drop trigger if exists handle_notes_update on public.notes;
create trigger handle_notes_update
    before update on public.notes
    for each row
    execute procedure public.handle_notes_update();

create table if not exists public.notes_items (
    id bigint generated by default as identity primary key,
    list_id bigint not null references public.notes(id) on delete cascade,
    child boolean not null,
    title text not null,
    position integer not null,
    created timestamptz not null default timezone('utc', now()),
    updated timestamptz not null default timezone('utc', now()),
    check_time timestamp default null,
    update_index bigint not null
);

create or replace view public.notes_with_counts as
select
    notes.id,
    notes.title,
    notes.created,
    notes.updated,
    count(notes_items.id)::int as items_count,
    count(notes_items.id) filter (where notes_items.check_time is null)::int as undone_items_count
from public.notes
left join public.notes_items
    on notes_items.list_id = notes.id
group by notes.id, notes.title, notes.created, notes.updated;

create or replace function public.handle_notes_items_update()
returns trigger
language plpgsql
as $$
begin
    if new.update_index <= old.update_index then
        raise exception
            '%',
            json_build_object(
                'id',
                'update_index_conflict',
                'text',
                format(
                    'update_index must be greater than current value (current %s, got %s)',
                    old.update_index,
                    new.update_index
                ),
                'current_update_index',
                old.update_index,
                'requested_update_index',
                new.update_index
            )::text;
    end if;

    new.updated = timezone('utc', now());
    return new;
end;
$$;

drop trigger if exists handle_notes_items_update on public.notes_items;
create trigger handle_notes_items_update
    before update on public.notes_items
    for each row
    execute procedure public.handle_notes_items_update();
